env:
  browser: false
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
   # Because mongoose and graphql works poorly with TypeScript,
   # it seems to be necessary to allow any as a type. 
  "@typescript-eslint/no-explicit-any": "off"
